# Configuration file
name: lechoo
sitename: lechoo
email: lechoo2u@gmail.com
markdown: kramdown
highlighter: pygments
permalink: /:categories/:title
auto: true
server: true
paginate: 3
sass:
  sass_dir: _sass
  style: :expanded