# Configuration file
name: lechoo
sitename: lechoo
email: lechoo2u@gmail.com
markdown: kramdown
highlighter: pygments
permalink: pretty
auto: true
server: true
paginate: 3
# Sass settings
sass:
  sass_dir: _sass
  style: :expanded